### PR TITLE
stageId fix to correct auth problems

### PR DESCRIPTION
**Pull request by kaschioudi**
@asmecher

### CODE REVIEW

**Comment by axfelix** [comment]
What was needed to trigger this issue in the first place so I know when I'm testing? It was working fine for me...

**Comment by asmecher** [comment]
@axfelix, the latest OJS release (and current `ojs-stable-3_1_1`) are more stringent around access policies than e.g. 3.1.0-0 was.

**Comment by axfelix** [comment]
ah, got it!

**Comment by asmecher** [comment]
At a glance, shouldn't https://github.com/kaschioudi/ojs3-markup/pull/63/files#diff-2b4d8aef38535ec865c6a5892f5f48a0R463 also have `stageId` rather than `stage` (and use `$stageId` rather than `$stage`)? I would think the Substance/Texture operations would also need the file stage ID in order to perform file operations.

**Comment by kaschioudi** [comment]
and yes! I had `git stash` those changes at some point.

**Comment by kaschioudi** [comment]
@axfelix and @asmecher : when you get a chance please try this and let me know. I have been having lot of trouble with my OJS installs these past day. But one thing I have noticed is that sometimes the xml file does not get added to the grid after conversion.

**Comment by axfelix** [comment]
I was having that problem earlier in testing several months ago, especially after very long (>10 minute) jobs when the server was busy, but I haven't encountered it in a while. If you're hitting it lately, it's probably a PHP timeout issue...

**Comment by kaschioudi** [comment]
thanks @axfelix for your feedback 👍

**Comment by axfelix** [comment]
@asmecher actually, I just realized I tested with 3.1.1 earlier this week before this PR and it worked fine...

**Comment by axfelix** [comment]
This branch doesn't seem to be returning XML to OJS properly, actually. The jobs submit, but I am encountering the issue @kaschioudi described above. But again, it was working fine for me on 3.1.1 on master.

**Comment by kaschioudi** [comment]
@axfelix : this commit (https://github.com/kaschioudi/ojs3-markup/commit/d3aa584433c77f3df77d9408d4be5294e872be3c) should fix the error I described above.

I will look into XML issue next.

**Comment by axfelix** [comment]
This branch is working fine for me now on 3.1.1 -- let me know what I should wait on, if anything, before merging.

**Pull request merged**
